version: '3'
services:
  mysql_db:
    container_name: cloud
    hostname: cloud
    image: mysql:8.1.0
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cloud
      - MYSQL_DATABASE=cloud
    restart: always
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql
  app:
    container_name: app
    hostname: app
    build: 
      context: .
      dockerfile: Dockerfile.service
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mysql_db
      
volumes:
  mysql_db:
